[package]
name = "maven_search_cmdline"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
maven-search-lib = { path = "../lib" }
getargs = "0.4.1"
log = "0.4.14"
env_logger = "0.9.0"
